name: Add GitHub issue to ClickUp task
on:
  issues:
    types:
      - labeled

env:
  LABEL_NAME: ${{ vars.CLICKUP_LABEL || 'planned' }}
  TITLE: ${{ github.event.issue.title }}
  BODY: ${{ github.event.issue.body }}

jobs:
  add-task:
    if: contains(github.event.label.name, ${{ vars.CLICKUP_LABEL || 'planned' }})
    runs-on: ubuntu-latest
    steps:
      - name: Send issue to ClickUp
        run: |
          labels=$(jq '.issue.labels | map(.name)' $GITHUB_EVENT_PATH)
          labels=${labels//"$LABEL_NAME"/"github"}
          echo "$labels"

          content=$(echo -e "$BODY\n\n${{ github.event.issue.html_url }}")
          content=$(echo "$content" | jq -Rs .)
          echo "$content"

          curl -X POST https://api.clickup.com/api/v2/list/${{ vars.CLICKUP_LIST_ID }}/task \
          -H "Authorization: ${{ secrets.CLICKUP_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "name": "'"$TITLE"' #${{ github.event.issue.number }}",
                "markdown_content": '"$content"',
                "tags": '"${labels}"'
              }'
