name: Publish Docker Image and Deploy

on:
  # when a push is made to the main branch (like when a pull request is merged, or something is pushed directly)
  workflow_dispatch:
  push:
    branches: [ "main", "add-instructions-to-pull-binary" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Calculate short_sha
      id: vars
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    # note: we don't use the --latest flag. this way, a particular short_sha
    # of cartogram-web can be used to identify the version of the executable
    # as internal/executable/release-tag.txt will specify version
    - name: Pull Executable
      run: |
        bash ${{github.workspace}}/tools/pull-executable.sh

    - name: Build and Publish Docker Image
      uses: elgohr/Publish-Docker-Github-Action@2.18
      with:
          name: gocartio/cartogram-web
          username: ${{ secrets.DOCKER_USERNAME }}
          # DOCKER_PASSWORD should not be your actual password, but a docker access token
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ steps.vars.outputs.short_sha }}"


    - name: Push tag
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag ${{ steps.vars.outputs.short_sha }}
        git push origin ${{ steps.vars.outputs.short_sha }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.vars.outputs.short_sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}