name: Publish Docker Image and Deploy

on:
  # when a push is made to the main branch (like when a pull request is merged, or something is pushed directly)
  workflow_dispatch:
  push:
    branches: [ "main", "add-instructions-to-pull-binary" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull Executable
      run: bash ${{github.workspace}}/internal/executable/pull-executable.sh

    - name: Build Docker image
      run: docker build -t cartogram-web:latest .